# Generated by Django 5.2.6 on 2025-09-29 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prediccionmorosidad',
            name='residente',
            field=models.ForeignKey(blank=True, help_text='Residente específico para predicción individual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicciones_morosidad_individual', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prediccionmorosidad',
            name='residente_especifico',
            field=models.BooleanField(default=False, help_text='Indica si la predicción es para un residente específico'),
        ),
        migrations.AlterField(
            model_name='prediccionmorosidad',
            name='modelo_usado',
            field=models.CharField(choices=[('grok-4-fast-free', 'Grok 4 Fast Free')], help_text='Modelo de IA utilizado', max_length=20),
        ),
    ]
