# Generated by Django 5.2 on 2025-09-24 15:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Área')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('salon_eventos', 'Salón de Eventos'), ('gimnasio', 'Gimnasio'), ('piscina', 'Piscina'), ('cancha_tenis', 'Cancha de Tenis'), ('cancha_futbol', 'Cancha de Fútbol'), ('sala_juntas', 'Sala de Juntas'), ('bbq', 'Área de BBQ'), ('otros', 'Otros')], max_length=20, verbose_name='Tipo de Área')),
                ('capacidad_maxima', models.PositiveIntegerField(help_text='Número máximo de personas', verbose_name='Capacidad Máxima')),
                ('costo_por_hora', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo por Hora')),
                ('costo_reserva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo fijo por reserva (adicional al costo por hora)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo de Reserva')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('mantenimiento', 'En Mantenimiento')], default='activa', max_length=15, verbose_name='Estado')),
                ('requiere_aprobacion', models.BooleanField(default=False, help_text='Si es True, la reserva debe ser aprobada por un administrador', verbose_name='Requiere Aprobación')),
                ('tiempo_minimo_reserva', models.PositiveIntegerField(default=1, help_text='Tiempo mínimo de reserva en horas', verbose_name='Tiempo Mínimo (horas)')),
                ('tiempo_maximo_reserva', models.PositiveIntegerField(default=8, help_text='Tiempo máximo de reserva en horas', verbose_name='Tiempo Máximo (horas)')),
                ('anticipo_minimo_horas', models.PositiveIntegerField(default=24, help_text='Horas mínimas de anticipación para reservar', verbose_name='Anticipación Mínima (horas)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Área Común',
                'verbose_name_plural': 'Áreas Comunes',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='HorarioDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10, verbose_name='Día de la Semana')),
                ('hora_apertura', models.TimeField(verbose_name='Hora de Apertura')),
                ('hora_cierre', models.TimeField(verbose_name='Hora de Cierre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('area_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disponibles', to='reservations.areacomun', verbose_name='Área Común')),
            ],
            options={
                'verbose_name': 'Horario Disponible',
                'verbose_name_plural': 'Horarios Disponibles',
                'ordering': ['area_comun', 'dia_semana'],
                'unique_together': {('area_comun', 'dia_semana')},
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Reserva')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('duracion_horas', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Duración (horas)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada'), ('usada', 'Usada')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo Total')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('numero_personas', models.PositiveIntegerField(default=1, verbose_name='Número de Personas')),
                ('motivo_cancelacion', models.TextField(blank=True, verbose_name='Motivo de Cancelación')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cancelación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservations.areacomun', verbose_name='Área Común')),
                ('cancelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_canceladas', to=settings.AUTH_USER_MODEL, verbose_name='Cancelada Por')),
                ('cargo_financiero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='finances.cargofinanciero', verbose_name='Cargo Financiero')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha', '-hora_inicio'],
                'unique_together': {('area_comun', 'fecha', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
