# Generated by Django 5.0 on 2025-09-13 06:30

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Concepto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('cuota_mensual', 'Cuota Mensual'), ('cuota_extraordinaria', 'Cuota Extraordinaria'), ('multa_ruido', 'Multa por Ruido'), ('multa_areas_comunes', 'Multa Áreas Comunes'), ('multa_estacionamiento', 'Multa Estacionamiento'), ('multa_mascota', 'Multa por Mascota'), ('otros', 'Otros')], max_length=30, verbose_name='Tipo de Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=15, verbose_name='Estado')),
                ('fecha_vigencia_desde', models.DateField(default=datetime.date.today, verbose_name='Vigente desde')),
                ('fecha_vigencia_hasta', models.DateField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('es_recurrente', models.BooleanField(default=False, help_text='Si se aplica automáticamente cada mes')),
                ('aplica_a_todos', models.BooleanField(default=True, help_text='Si aplica a todos los residentes o solo a casos específicos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_financieros_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Concepto Financiero',
                'verbose_name_plural': 'Conceptos Financieros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CargoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto a Pagar')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15, verbose_name='Estado del Cargo')),
                ('fecha_aplicacion', models.DateField(default=datetime.date.today, verbose_name='Fecha de Aplicación')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('referencia_pago', models.CharField(blank=True, max_length=100, verbose_name='Referencia de Pago')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('aplicado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos_aplicados_por_mi', to=settings.AUTH_USER_MODEL)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_financieros', to=settings.AUTH_USER_MODEL)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos_aplicados', to='finances.conceptofinanciero')),
            ],
            options={
                'verbose_name': 'Cargo Financiero',
                'verbose_name_plural': 'Cargos Financieros',
                'ordering': ['-fecha_aplicacion', 'estado'],
            },
        ),
        migrations.AddIndex(
            model_name='conceptofinanciero',
            index=models.Index(fields=['tipo', 'estado'], name='finances_co_tipo_7a0d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptofinanciero',
            index=models.Index(fields=['fecha_vigencia_desde', 'fecha_vigencia_hasta'], name='finances_co_fecha_v_fd1905_idx'),
        ),
        migrations.AddIndex(
            model_name='cargofinanciero',
            index=models.Index(fields=['residente', 'estado'], name='finances_ca_residen_59211f_idx'),
        ),
        migrations.AddIndex(
            model_name='cargofinanciero',
            index=models.Index(fields=['fecha_vencimiento', 'estado'], name='finances_ca_fecha_v_dcab5a_idx'),
        ),
        migrations.AddIndex(
            model_name='cargofinanciero',
            index=models.Index(fields=['concepto', 'fecha_aplicacion'], name='finances_ca_concept_c3aa20_idx'),
        ),
    ]
