# Generated by Django 5.2.6 on 2025-09-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='document_type',
            field=models.CharField(blank=True, choices=[('CI', 'Cédula de Identidad'), ('PASSPORT', 'Pasaporte'), ('RUC', 'RUC'), ('NIT', 'NIT')], default='CI', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='unit_number',
            field=models.CharField(blank=True, help_text='Número de unidad (solo para residentes)', max_length=20),
        ),
    ]
