# Generated by Django 5.0 on 2025-09-13 06:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('total_actividades', models.PositiveIntegerField(default=0, verbose_name='Total de Actividades')),
                ('total_logins', models.PositiveIntegerField(default=0, verbose_name='Total de Logins')),
                ('total_usuarios_activos', models.PositiveIntegerField(default=0, verbose_name='Usuarios Activos')),
                ('actividades_criticas', models.PositiveIntegerField(default=0, verbose_name='Actividades Críticas')),
                ('errores_sistema', models.PositiveIntegerField(default=0, verbose_name='Errores del Sistema')),
                ('datos_estadisticas', models.JSONField(blank=True, null=True, verbose_name='Datos Estadísticos Detallados')),
            ],
            options={
                'verbose_name': 'Estadística de Auditoría',
                'verbose_name_plural': 'Estadísticas de Auditoría',
                'ordering': ['-fecha'],
                'unique_together': {('fecha',)},
            },
        ),
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_session', models.CharField(max_length=255, unique=True, verbose_name='Token de Sesión')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('fecha_ultimo_acceso', models.DateTimeField(auto_now=True, verbose_name='Último Acceso')),
                ('esta_activa', models.BooleanField(default=True, verbose_name='Sesión Activa')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión de Usuario',
                'verbose_name_plural': 'Sesiones de Usuario',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('crear', 'Crear registro'), ('actualizar', 'Actualizar registro'), ('eliminar', 'Eliminar registro'), ('ver', 'Ver registro'), ('pago', 'Procesar pago'), ('asignar_rol', 'Asignar rol'), ('cambiar_password', 'Cambiar contraseña'), ('acceso_denegado', 'Acceso denegado'), ('error_sistema', 'Error del sistema'), ('exportar', 'Exportar datos'), ('importar', 'Importar datos'), ('configurar', 'Configurar sistema')], max_length=20, verbose_name='Tipo de Actividad')),
                ('descripcion', models.TextField(help_text='Descripción detallada de la actividad', verbose_name='Descripción')),
                ('nivel_importancia', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='medio', max_length=10, verbose_name='Nivel de Importancia')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del Objeto')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('datos_adicionales', models.JSONField(blank=True, help_text='Información adicional en formato JSON', null=True, verbose_name='Datos Adicionales')),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Estado anterior del objeto (para cambios)', null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Nuevo estado del objeto (para cambios)', null=True, verbose_name='Datos Nuevos')),
                ('es_exitoso', models.BooleanField(default=True, verbose_name='Operación Exitosa')),
                ('mensaje_error', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Tipo de Objeto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['usuario', '-timestamp'], name='audit_regis_usuario_6e455f_idx'), models.Index(fields=['tipo_actividad', '-timestamp'], name='audit_regis_tipo_ac_b10ae1_idx'), models.Index(fields=['nivel_importancia', '-timestamp'], name='audit_regis_nivel_i_3b9edb_idx'), models.Index(fields=['-timestamp'], name='audit_regis_timesta_7f2abe_idx')],
            },
        ),
    ]
