# Generated by Django 5.0 on 2025-09-14 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id_areacomun', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horario_disponible', models.CharField(blank=True, max_length=100, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Área Común',
                'verbose_name_plural': 'Áreas Comunes',
                'db_table': 'area_comun',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id_camara', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('url_stream', models.URLField(blank=True, max_length=500, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cámara',
                'verbose_name_plural': 'Cámaras',
                'db_table': 'camara',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida')], default='pendiente', max_length=20)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'db_table': 'cuota',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id_tipoevento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Eventos',
                'db_table': 'tipo_evento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UnidadHabitacional',
            fields=[
                ('id_unidadhabitacional', models.AutoField(primary_key=True, serialize=False)),
                ('identificador', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('metros_cuadrados', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unidad Habitacional',
                'verbose_name_plural': 'Unidades Habitacionales',
                'db_table': 'unidad_habitacional',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(choices=[('propietario', 'Propietario'), ('inquilino', 'Inquilino'), ('administrador', 'Administrador'), ('seguridad', 'Seguridad')], default='propietario', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('efectivo', 'Efectivo'), ('digital', 'Digital')], max_length=20)),
                ('comprobante_url', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='completado', max_length=20)),
                ('id_cuota', models.ForeignKey(db_column='id_cuota', on_delete=django.db.models.deletion.CASCADE, to='condominio.cuota')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('urgente', 'Urgente')], default='correctivo', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=20)),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('asignado', 'Asignado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_unidadhabitacional', models.ForeignKey(db_column='id_unidadhabitacional', on_delete=django.db.models.deletion.CASCADE, to='condominio.unidadhabitacional')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'mantenimiento',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cuota',
            name='id_unidadhabitacional',
            field=models.ForeignKey(db_column='id_unidadhabitacional', on_delete=django.db.models.deletion.CASCADE, to='condominio.unidadhabitacional'),
        ),
        migrations.AddField(
            model_name='unidadhabitacional',
            name='id_usuarioinquilino',
            field=models.ForeignKey(blank=True, db_column='id_usuarioinquilino', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades_inquilino', to='condominio.usuario'),
        ),
        migrations.AddField(
            model_name='unidadhabitacional',
            name='id_usuariopropietario',
            field=models.ForeignKey(db_column='id_usuariopropietario', on_delete=django.db.models.deletion.RESTRICT, related_name='propiedades_propietario', to='condominio.usuario'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_areacomun', models.ForeignKey(db_column='id_areacomun', on_delete=django.db.models.deletion.RESTRICT, to='condominio.areacomun')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='condominio.usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_reporte', models.CharField(choices=[('financiero', 'Financiero'), ('reservas', 'Reservas'), ('seguridad', 'Seguridad'), ('mantenimiento', 'Mantenimiento')], max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('parametros', models.JSONField(blank=True, null=True)),
                ('url_reporte', models.CharField(max_length=500)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='condominio.usuario')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reporte',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('registroafectado', models.IntegerField(blank=True, null=True)),
                ('tabla_afectada', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=20)),
                ('valores_anteriores', models.JSONField(blank=True, null=True)),
                ('valores_nuevos', models.JSONField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='condominio.usuario')),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
                'db_table': 'bitacora',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id_aviso', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=20)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='condominio.usuario')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'db_table': 'aviso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VehiculoAutorizado',
            fields=[
                ('id_vehiculoautorizado', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='condominio.usuario')),
            ],
            options={
                'verbose_name': 'Vehículo Autorizado',
                'verbose_name_plural': 'Vehículos Autorizados',
                'db_table': 'vehiculo_autorizado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EventoSeguridad',
            fields=[
                ('id_eventoseguridad', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('evidencia_url', models.CharField(blank=True, max_length=500, null=True)),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('revisado', models.BooleanField(default=False)),
                ('id_camara', models.ForeignKey(db_column='id_camara', on_delete=django.db.models.deletion.CASCADE, to='condominio.camara')),
                ('id_tipoevento', models.ForeignKey(db_column='id_tipoevento', on_delete=django.db.models.deletion.RESTRICT, to='condominio.tipoevento')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='condominio.usuario')),
                ('id_vehiculoautorizado', models.ForeignKey(blank=True, db_column='id_vehiculoautorizado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='condominio.vehiculoautorizado')),
            ],
            options={
                'verbose_name': 'Evento de Seguridad',
                'verbose_name_plural': 'Eventos de Seguridad',
                'db_table': 'evento_seguridad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('id_areacomun', models.ForeignKey(db_column='id_areacomun', on_delete=django.db.models.deletion.CASCADE, to='condominio.areacomun')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'db_table': 'zona',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='camara',
            name='id_zona',
            field=models.ForeignKey(db_column='id_zona', on_delete=django.db.models.deletion.CASCADE, to='condominio.zona'),
        ),
    ]
