# Generated by Django 5.2 on 2025-09-24 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_push', models.CharField(help_text='Token FCM o web push', max_length=500, unique=True)),
                ('tipo_dispositivo', models.CharField(choices=[('web', 'Web Browser'), ('android', 'Android'), ('ios', 'iOS'), ('flutter_web', 'Flutter Web')], max_length=20)),
                ('nombre_dispositivo', models.CharField(blank=True, help_text='Nombre descriptivo del dispositivo', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['-ultima_actividad'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('acceso_permitido', 'Acceso Permitido'), ('acceso_denegado', 'Acceso Denegado'), ('nuevo_mensaje', 'Nuevo Mensaje'), ('pago_realizado', 'Pago Realizado'), ('pago_pendiente', 'Pago Pendiente'), ('mantenimiento', 'Aviso de Mantenimiento'), ('emergencia', 'Emergencia'), ('recordatorio', 'Recordatorio'), ('sistema', 'Sistema')], default='sistema', max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('fallida', 'Fallida'), ('leida', 'Leída')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('datos_extra', models.JSONField(blank=True, help_text='Datos adicionales en formato JSON', null=True)),
                ('prioridad', models.IntegerField(default=1, help_text='Prioridad (1-5, siendo 5 la más alta)')),
                ('push_enviado', models.BooleanField(default=False)),
                ('email_enviado', models.BooleanField(default=False)),
                ('sms_enviado', models.BooleanField(default=False)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='modulo_notificaciones.dispositivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', '-fecha_creacion'], name='modulo_noti_usuario_8f1eef_idx'), models.Index(fields=['estado', 'tipo'], name='modulo_noti_estado_21efe9_idx'), models.Index(fields=['fecha_creacion'], name='modulo_noti_fecha_c_842b94_idx')],
            },
        ),
        migrations.CreateModel(
            name='PreferenciasNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_notificacion', models.CharField(choices=[('acceso_permitido', 'Acceso Permitido'), ('acceso_denegado', 'Acceso Denegado'), ('nuevo_mensaje', 'Nuevo Mensaje'), ('pago_realizado', 'Pago Realizado'), ('pago_pendiente', 'Pago Pendiente'), ('mantenimiento', 'Aviso de Mantenimiento'), ('emergencia', 'Emergencia'), ('recordatorio', 'Recordatorio')], max_length=50)),
                ('push_enabled', models.BooleanField(default=True, help_text='Enviar notificación push')),
                ('email_enabled', models.BooleanField(default=False, help_text='Enviar notificación por email')),
                ('sms_enabled', models.BooleanField(default=False, help_text='Enviar notificación por SMS')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificación',
                'ordering': ['usuario', 'tipo_notificacion'],
                'unique_together': {('usuario', 'tipo_notificacion')},
            },
        ),
    ]
