# Generated by Django 5.0 on 2025-09-13 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del aviso', max_length=200)),
                ('contenido', models.TextField(help_text='Contenido detallado del aviso')),
                ('resumen', models.CharField(blank=True, help_text='Resumen corto para notificaciones', max_length=500)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('archivado', 'Archivado'), ('vencido', 'Vencido')], default='borrador', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('tipo_destinatario', models.CharField(choices=[('todos', 'Todos los usuarios'), ('residentes', 'Solo residentes'), ('administradores', 'Solo administradores'), ('seguridad', 'Solo personal de seguridad'), ('admin_seguridad', 'Administradores y seguridad'), ('residentes_seguridad', 'Residentes y seguridad'), ('personalizado', 'Selección personalizada')], default='todos', max_length=30)),
                ('roles_destinatarios', models.JSONField(blank=True, default=list, help_text="Lista de roles específicos cuando tipo_destinatario es 'personalizado'")),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, help_text='Opcional: fecha de vencimiento del aviso', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('requiere_confirmacion', models.BooleanField(default=False, help_text='Si los destinatarios deben confirmar lectura')),
                ('adjunto', models.FileField(blank=True, help_text='Archivo adjunto opcional', null=True, upload_to='avisos/adjuntos/')),
                ('visualizaciones', models.PositiveIntegerField(default=0)),
                ('es_fijado', models.BooleanField(default=False, help_text='Aviso fijado al inicio de la lista')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_creados', to=settings.AUTH_USER_MODEL)),
                ('usuarios_destinatarios', models.ManyToManyField(blank=True, help_text='Usuarios específicos adicionales', related_name='avisos_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-es_fijado', '-fecha_publicacion', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='communications.aviso')),
                ('es_respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='communications.comentarioaviso')),
            ],
            options={
                'verbose_name': 'Comentario de Aviso',
                'verbose_name_plural': 'Comentarios de Avisos',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LecturaAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lectura', models.DateTimeField(auto_now_add=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='communications.aviso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lectura de Aviso',
                'verbose_name_plural': 'Lecturas de Avisos',
                'ordering': ['-fecha_lectura'],
                'unique_together': {('aviso', 'usuario')},
            },
        ),
    ]
