# Generated by Django 5.2 on 2025-09-24 16:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RostroRegistrado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_identificador', models.CharField(help_text='Nombre descriptivo del rostro', max_length=100)),
                ('imagen_rostro', models.ImageField(help_text='Imagen del rostro para reconocimiento', upload_to='rostros/')),
                ('embedding_ia', models.JSONField(help_text='Vector de características extraído por IA')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('confianza_minima', models.FloatField(default=0.85, help_text='Confianza mínima para reconocimiento (0-1)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rostros_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rostro Registrado',
                'verbose_name_plural': 'Rostros Registrados',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='VehiculoRegistrado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placa', models.CharField(help_text='Placa del vehículo (formato: 123ABC o 1234ABC)', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de placa inválido. Use formato: 123ABC o 1234ABC', regex='^\\d{3,4}[A-Z]{3}$')])),
                ('marca', models.CharField(help_text='Marca del vehículo', max_length=50)),
                ('modelo', models.CharField(help_text='Modelo del vehículo', max_length=50)),
                ('color', models.CharField(help_text='Color del vehículo', max_length=30)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehículo Registrado',
                'verbose_name_plural': 'Vehículos Registrados',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_acceso', models.CharField(choices=[('facial', 'Reconocimiento Facial'), ('placa', 'Lectura de Placa'), ('manual', 'Acceso Manual'), ('codigo', 'Código de Acceso')], default='manual', max_length=20)),
                ('estado', models.CharField(choices=[('permitido', 'Acceso Permitido'), ('denegado', 'Acceso Denegado'), ('pendiente', 'Pendiente de Verificación')], default='pendiente', max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.CharField(help_text='Punto de acceso (ej: Puerta Principal)', max_length=100)),
                ('confianza_ia', models.FloatField(blank=True, help_text='Confianza de la IA (0-1)', null=True)),
                ('datos_ia', models.JSONField(blank=True, help_text='Datos adicionales de la IA', null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_autorizados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos', to=settings.AUTH_USER_MODEL)),
                ('rostro_detectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos', to='modulo_ia.rostroregistrado')),
                ('vehiculo_detectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos', to='modulo_ia.vehiculoregistrado')),
            ],
            options={
                'verbose_name': 'Acceso',
                'verbose_name_plural': 'Historial de Accesos',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['fecha_hora'], name='modulo_ia_a_fecha_h_3385d2_idx'), models.Index(fields=['usuario', 'fecha_hora'], name='modulo_ia_a_usuario_95c538_idx'), models.Index(fields=['tipo_acceso', 'estado'], name='modulo_ia_a_tipo_ac_2de85e_idx')],
            },
        ),
    ]
